import fs from 'fs';
import test from 'tape';
import { parseXML } from '../lib/index.js';

const src = fs.readFileSync('test/data/css-selectors.xml', 'utf8');
const dom = parseXML(src);

test('querySelectorAll', t => {
  const qsa = sel => dom.root.querySelectorAll(sel).length;
  t.is(qsa('a.url.fn'), 2, 'a.url.fn');
  t.is(qsa('a.url, a.fn'), 2, 'a.url, a.fn');
  t.is(qsa('li[class]:nth-of-type(2n+1)'), 18, 'li[class]:nth-of-type(2n+1)');
  t.is(qsa('*[class]:nth-of-type(2n+1)'), 160, '*[class]:nth-of-type(2n+1)');
  t.is(qsa('li:nth-of-type(2n+1)'), 55, 'li:nth-of-type(2n+1)');
  t.is(qsa('li:nth-of-type(2n+2)'), 44, 'li:nth-of-type(2n+2)');
  t.is(qsa('li:nth-of-type(2n+3)'), 31, 'li:nth-of-type(2n+3)');
  t.is(qsa('li:nth-of-type(2n+4)'), 23, 'li:nth-of-type(2n+4)');
  t.is(qsa('li:nth-last-of-type(2n+1)'), 55, 'li:nth-last-of-type(2n+1)');
  t.is(qsa('li:nth-last-of-type(2n+2)'), 44, 'li:nth-last-of-type(2n+2)');
  t.is(qsa('li:nth-last-of-type(2n+3)'), 31, 'li:nth-last-of-type(2n+3)');
  t.is(qsa('li:nth-last-of-type(2n+4)'), 23, 'li:nth-last-of-type(2n+4)');
  t.is(qsa('li:nth-of-type(1n)'), 99, 'li:nth-of-type(1n)');
  t.is(qsa('li:nth-of-type(2n)'), 44, 'li:nth-of-type(2n)');
  t.is(qsa('li:nth-of-type(3n)'), 26, 'li:nth-of-type(3n)');
  t.is(qsa('li:nth-of-type(4n)'), 15, 'li:nth-of-type(4n)');
  t.is(qsa('li:nth-last-of-type(1n)'), 99, 'li:nth-last-of-type(1n)');
  t.is(qsa('li:nth-last-of-type(2n)'), 44, 'li:nth-last-of-type(2n)');
  t.is(qsa('li:nth-last-of-type(3n)'), 26, 'li:nth-last-of-type(3n)');
  t.is(qsa('li:nth-last-of-type(4n)'), 15, 'li:nth-last-of-type(4n)');
  t.is(qsa('li:nth-of-type(1)'), 24, 'li:nth-of-type(1)');
  t.is(qsa('li:nth-of-type(2)'), 21, 'li:nth-of-type(2)');
  t.is(qsa('li:nth-of-type(3)'), 15, 'li:nth-of-type(3)');
  t.is(qsa('li:nth-of-type(4)'), 9, 'li:nth-of-type(4)');
  t.is(qsa('li:nth-last-of-type(1)'), 24, 'li:nth-last-of-type(1)');
  t.is(qsa('li:nth-last-of-type(2)'), 21, 'li:nth-last-of-type(2)');
  t.is(qsa('li:nth-last-of-type(3)'), 15, 'li:nth-last-of-type(3)');
  t.is(qsa('li:nth-last-of-type(4)'), 9, 'li:nth-last-of-type(4)');
  t.is(qsa('div:nth-child(2n+1)'), 26, 'div:nth-child(2n+1)');
  t.is(qsa('div:nth-child(2n+2)'), 25, 'div:nth-child(2n+2)');
  t.is(qsa('div:nth-child(2n+3)'), 25, 'div:nth-child(2n+3)');
  t.is(qsa('div:nth-child(2n+4)'), 25, 'div:nth-child(2n+4)');
  t.is(qsa('div:nth-last-child(2n+1)'), 24, 'div:nth-last-child(2n+1)');
  t.is(qsa('div:nth-last-child(2n+2)'), 27, 'div:nth-last-child(2n+2)');
  t.is(qsa('div:nth-last-child(2n+3)'), 23, 'div:nth-last-child(2n+3)');
  t.is(qsa('div:nth-last-child(2n+4)'), 27, 'div:nth-last-child(2n+4)');
  t.is(qsa('div:nth-child(1n)'), 51, 'div:nth-child(1n)');
  t.is(qsa('div:nth-child(2n)'), 25, 'div:nth-child(2n)');
  t.is(qsa('div:nth-child(3n)'), 18, 'div:nth-child(3n)');
  t.is(qsa('div:nth-child(4n)'), 15, 'div:nth-child(4n)');
  t.is(qsa('div:nth-last-child(1n)'), 51, 'div:nth-last-child(1n)');
  t.is(qsa('div:nth-last-child(2n)'), 27, 'div:nth-last-child(2n)');
  t.is(qsa('div:nth-last-child(3n)'), 16, 'div:nth-last-child(3n)');
  t.is(qsa('div:nth-last-child(4n)'), 17, 'div:nth-last-child(4n)');
  t.is(qsa('div:nth-child(1)'), 1, 'div:nth-child(1)');
  t.is(qsa('div:nth-child(2)'), 0, 'div:nth-child(2)');
  t.is(qsa('div:nth-child(3)'), 0, 'div:nth-child(3)');
  t.is(qsa('div:nth-child(4)'), 2, 'div:nth-child(4)');
  t.is(qsa('div:nth-last-child(1)'), 1, 'div:nth-last-child(1)');
  t.is(qsa('div:nth-last-child(2)'), 0, 'div:nth-last-child(2)');
  t.is(qsa('div:nth-last-child(3)'), 0, 'div:nth-last-child(3)');
  t.is(qsa('div:nth-last-child(4)'), 1, 'div:nth-last-child(4)');
  t.is(qsa('div:nth-child(even)'), 25, 'div:nth-child(even)');
  t.is(qsa('div:nth-child(odd)'), 26, 'div:nth-child(odd)');
  t.is(qsa('div:nth-child(n)'), 51, 'div:nth-child(n)');
  t.is(qsa('div:nth-last-child(even)'), 27, 'div:nth-last-child(even)');
  t.is(qsa('div:nth-last-child(odd)'), 24, 'div:nth-last-child(odd)');
  t.is(qsa('div:nth-last-child(n)'), 51, 'div:nth-last-child(n)');
  t.is(qsa('div:first-of-type'), 3, 'div:first-of-type');
  t.is(qsa('div:last-of-type'), 3, 'div:last-of-type');
  t.is(qsa('div:only-of-type'), 2, 'div:only-of-type');
  t.is(qsa('div:nth-of-type(even)'), 24, 'div:nth-of-type(even)');
  t.is(qsa('div:nth-of-type(2n)'), 24, 'div:nth-of-type(2n)');
  t.is(qsa('div:nth-of-type(odd)'), 27, 'div:nth-of-type(odd)');
  t.is(qsa('div:nth-of-type(2n+1)'), 27, 'div:nth-of-type(2n+1)');
  t.is(qsa('div:nth-of-type(n)'), 51, 'div:nth-of-type(n)');
  t.is(qsa('div:nth-last-of-type(even)'), 24, 'div:nth-last-of-type(even)');
  t.is(qsa('div:nth-last-of-type(2n)'), 24, 'div:nth-last-of-type(2n)');
  t.is(qsa('div:nth-last-of-type(odd)'), 27, 'div:nth-last-of-type(odd)');
  t.is(qsa('div:nth-last-of-type(2n+1)'), 27, 'div:nth-last-of-type(2n+1)');
  t.is(qsa('div:nth-last-of-type(n)'), 51, 'div:nth-last-of-type(n)');
  t.is(qsa('label[for]'), 0, 'label[for]');
  t.is(qsa('*'), 1778, '*');
  t.is(qsa('body'), 0, 'body');
  t.is(qsa('div'), 51, 'div');
  t.is(qsa('body div'), 0, 'body div');
  t.is(qsa('div div'), 2, 'div div');
  t.is(qsa('div div div'), 0, 'div div div');
  t.is(qsa('div p'), 140, 'div p');
  t.is(qsa('div > p'), 134, 'div > p');
  t.is(qsa('div + p'), 22, 'div + p');
  t.is(qsa('div ~ p'), 183, 'div ~ p');
  t.is(qsa('div.example ~ p'), 152, 'div.example ~ p');
  t.is(qsa('div[class^=exa][class$=mple]'), 43, 'div[class^=exa][class$=mple]');
  t.is(qsa('div p a'), 12, 'div p a');
  t.is(qsa('div, p, a'), 671, 'div, p, a');
  t.is(qsa('.note'), 14, '.note');
  t.is(qsa('div.example'), 43, 'div.example');
  t.is(qsa('ul .tocline2'), 12, 'ul .tocline2');
  t.is(qsa('div.example, div.note'), 44, 'div.example, div.note');
  t.is(qsa('#title'), 1, '#title');
  t.is(qsa('h1#title'), 1, 'h1#title');
  t.is(qsa('div #title'), 1, 'div #title');
  t.is(qsa('ul.toc li.tocline2'), 12, 'ul.toc li.tocline2');
  t.is(qsa('ul.toc > li.tocline2'), 12, 'ul.toc > li.tocline2');
  t.is(qsa('h1#title + div > p'), 0, 'h1#title + div > p');
  t.is(qsa('h1[id]:contains(Selectors)'), 1, 'h1[id]:contains(Selectors)');
  t.is(qsa('a[href][lang][class]'), 1, 'a[href][lang][class]');
  t.is(qsa('div[class]'), 51, 'div[class]');
  t.is(qsa('div[class=example]'), 43, 'div[class=example]');
  t.is(qsa('div[class^=exa]'), 43, 'div[class^=exa]');
  t.is(qsa('div[class$=mple]'), 43, 'div[class$=mple]');
  t.is(qsa('div[class*=e]'), 50, 'div[class*=e]');
  t.is(qsa('div[class|=dialog]'), 0, 'div[class|=dialog]');
  t.is(qsa('div[class!=made_up]'), 51, 'div[class!=made_up]');
  t.is(qsa('div[class~=example]'), 43, 'div[class~=example]');
  t.is(qsa('div:not(.example)'), 8, 'div:not(.example)');
  t.is(qsa('p:contains(selectors)'), 54, 'p:contains(selectors)');
  t.is(qsa('p:nth-child(even)'), 158, 'p:nth-child(even)');
  t.is(qsa('p:nth-child(2n)'), 158, 'p:nth-child(2n)');
  t.is(qsa('p:nth-child(odd)'), 166, 'p:nth-child(odd)');
  t.is(qsa('p:nth-child(2n+1)'), 166, 'p:nth-child(2n+1)');
  t.is(qsa('p:nth-child(n)'), 324, 'p:nth-child(n)');
  t.is(qsa('p:only-child'), 3, 'p:only-child');
  t.is(qsa('p:last-child'), 19, 'p:last-child');
  t.is(qsa('p:first-child'), 54, 'p:first-child');
  t.end();
});
